/* SEO foundation for abhinavbajpai.in */
(function(){
  const base='https://abhinavbajpai.in';
  const file=(location.pathname.split('/').pop()||'index.html').toLowerCase();
  const pages={
    'index.html':{title:'Abhinav Bajpai | Supply Chain Professional & Commercial Leader',description:'Abhinav Bajpai is a supply chain professional and commercial leader with 15+ years across AWL Agri Business (formerly Adani Wilmar), Mundra operations, procurement, logistics, global trade, GST, Customs and commercial automation.',keywords:'Abhinav Bajpai, supply chain professional, supply chain leader, commercial leader, supply chain management India, supply chain consultant, supply chain consultation, Adani Wilmar, AWL Agri Business, Mundra, procurement, logistics, global trade, GST, Customs, supply chain automation'},
    'profile.html':{title:'Profile | Abhinav Bajpai — Commercial & Supply Chain Leader',description:'Executive profile covering commercial leadership, supply chain, procurement, exports, finance, warehouse, logistics, GST, Customs and data-driven operations.',keywords:'Abhinav Bajpai profile, supply chain, commercial operations, procurement, warehouse, dispatch, GST, Customs, exports, imports'},
    'experience.html':{title:'Experience | Abhinav Bajpai — 15+ Years Supply Chain Professional',description:'15+ years of commercial and supply-chain experience across AWL Agri Business (formerly Adani Wilmar), Mundra, Roca and Action Construction Equipment.',keywords:'Abhinav Bajpai experience, supply chain professional, supply chain experience, AWL, Adani Wilmar, Mundra, exports, finance, warehouse, procurement, logistics, commercial'},
    'capabilities.html':{title:'Supply Chain Capabilities | Abhinav Bajpai — India',description:'Supply chain and commercial capabilities across procurement, logistics, global trade, operations, GST, Customs, MIS and process automation.',keywords:'supply chain capabilities, supply chain professional, supply chain management, supply chain procurement, logistics, commercial operations, global trade, GST, Customs, Excel automation, MIS, SAP, Abhinav Bajpai'},
    'impact.html':{title:'Supply Chain Impact | Abhinav Bajpai — Mundra & AWL',description:'Supply-chain operating scale and commercial outcomes from Abhinav Bajpai’s experience at AWL Agri Business, formerly Adani Wilmar, including Mundra operations.',keywords:'supply chain impact, supply chain professional, AWL Agri Business, Adani Wilmar, Mundra supply chain, commercial impact, 700 vehicles, liquid cargo, automation, Abhinav Bajpai'},
    'case-studies.html':{title:'Case Studies | Abhinav Bajpai — Supply Chain & Commercial Transformation',description:'Flagship case studies covering commercial automation, dispatch, liquid cargo, GST analytics, global trade and procurement.',keywords:'supply chain case studies, commercial automation, dispatch, liquid cargo, GST analytics, global trade, procurement'},
    'projects.html':{title:'Supply Chain Projects | Abhinav Bajpai — Logistics, Trade & Automation',description:'Selected supply-chain, commercial, GST, logistics, global trade, procurement and automation projects by Abhinav Bajpai.',keywords:'supply chain projects, supply chain professional, GST analysis, E-Way Bill, logistics, inventory, exports, global trade, procurement, Excel automation'},
    'awards.html':{title:'Awards & Recognition | Abhinav Bajpai — Supply Chain Professional',description:'Recognition, promotions, scholarship and professional achievements of Abhinav Bajpai across commercial and supply-chain leadership.',keywords:'Abhinav Bajpai awards, supply chain professional recognition, AWL recognition, Adani Wilmar, Employee of the Month, Long Service Award, MIT MicroMasters'},
    'contact.html':{title:'Supply Chain Consultation | Abhinav Bajpai — India',description:'Supply chain consultation and commercial advisory by Abhinav Bajpai, a 15+ year supply chain professional with AWL Agri Business, formerly Adani Wilmar, and experience across procurement, logistics, global trade, GST, Customs and automation.',keywords:'supply chain consultation, supply chain consultant India, supply chain professional India, Abhinav Bajpai consultant, commercial consultant, supply chain advisory, procurement consultant, logistics consultant, Adani Wilmar supply chain, AWL Agri Business'}
  };
  const p=pages[file]||pages['index.html'];
  const canonical=base+(file==='index.html'?'':('/'+file));
  document.title=p.title;
  const set=(name,content)=>{let el=document.querySelector('meta[name="'+name+'"]');if(!el){el=document.createElement('meta');el.name=name;document.head.appendChild(el)}el.content=content};
  set('description',p.description);set('keywords',p.keywords);set('robots','index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1');
  let link=document.querySelector('link[rel="canonical"]');if(!link){link=document.createElement('link');link.rel='canonical';document.head.appendChild(link)}link.href=canonical;
  const og={'og:type':'website','og:url':canonical,'og:title':p.title,'og:description':p.description,'og:site_name':'Abhinav Bajpai','og:locale':'en_IN','og:image':base+'/assets/abhinav-bajpai-professional.png','twitter:card':'summary_large_image','twitter:title':p.title,'twitter:description':p.description,'twitter:image':base+'/assets/abhinav-bajpai-professional.png'};
  Object.entries(og).forEach(([name,content])=>{let el=document.querySelector('meta[property="'+name+'"],meta[name="'+name+'"]');if(!el){el=document.createElement('meta');if(name.startsWith('twitter:'))el.name=name;else el.setAttribute('property',name);document.head.appendChild(el)}el.content=content});
  const person={'@type':'Person','@id':base+'/#person','name':'Abhinav Bajpai','url':base+'/','image':base+'/assets/abhinav-bajpai-professional.png','jobTitle':'Associate Manager — Commercial & Supply Chain','description':'Commercial and Supply Chain professional with 15+ years of experience across procurement, logistics, imports, exports, finance, warehouse, dispatch, GST, Customs and process automation.','sameAs':['https://www.linkedin.com/in/abhinavbajpai'],'worksFor':{'@type':'Organization','name':'AWL Agri Business Limited','url':'https://www.awl.in/'},'knowsAbout':['Supply Chain Management','Commercial Operations','Procurement','Warehouse Operations','Dispatch','Logistics','Imports','Exports','GST','Customs','E-Way Bills','Invoice Controls','Excel Automation','MIS','Mundra Port Operations','Liquid Cargo','Stores Management']};
  const graph=[person,{'@type':'WebSite','@id':base+'/#website','url':base+'/','name':'Abhinav Bajpai — Commercial & Supply Chain Leader','publisher':{'@id':base+'/#person'}},{'@type':'WebPage','@id':canonical+'#webpage','url':canonical,'name':p.title,'description':p.description,'isPartOf':{'@id':base+'/#website'},'about':{'@id':base+'/#person'},'inLanguage':'en-IN','keywords':p.keywords}];
  let ld=document.getElementById('abhinav-seo-jsonld');if(!ld){ld=document.createElement('script');ld.id='abhinav-seo-jsonld';ld.type='application/ld+json';document.head.appendChild(ld)}ld.textContent=JSON.stringify({'@context':'https://schema.org','@graph':graph});
})();
