/* SEO foundation for abhinavbajpai.in */
(function(){
  const base='https://abhinavbajpai.in';
  const file=(location.pathname.split('/').pop()||'index.html').toLowerCase();
  const pages={
    'index.html':{title:'Abhinav Bajpai | Commercial & Supply Chain Leader',description:'Abhinav Bajpai is a Commercial & Supply Chain Leader with 15+ years across high-volume operations, procurement, logistics, global trade, GST, Customs and commercial automation.',keywords:'Abhinav Bajpai, supply chain professional, commercial leader, procurement, logistics, Mundra, AWL Agribusiness, Adani Wilmar, exports, imports, GST, Customs, Excel automation'},
    'profile.html':{title:'Profile | Abhinav Bajpai — Commercial & Supply Chain Leader',description:'Executive profile covering commercial leadership, supply chain, procurement, exports, finance, warehouse, logistics, GST, Customs and data-driven operations.',keywords:'Abhinav Bajpai profile, supply chain, commercial operations, procurement, warehouse, dispatch, GST, Customs, exports, imports'},
    'experience.html':{title:'Experience | Abhinav Bajpai — 15+ Years Commercial & Supply Chain',description:'Career experience across AWL Agribusiness, former Adani Wilmar, Roca and Action Construction Equipment, spanning commercial, exports, finance, warehouse, procurement and logistics.',keywords:'Abhinav Bajpai experience, AWL, Adani Wilmar, Mundra, exports, finance, warehouse, procurement, logistics, commercial'},
    'capabilities.html':{title:'Capabilities | Abhinav Bajpai — Commercial, Supply Chain & Procurement',description:'Commercial, supply-chain, procurement, global-trade, operations, compliance and digital capabilities of Abhinav Bajpai.',keywords:'commercial capabilities, supply chain capabilities, procurement, global trade, GST, Customs, Excel automation, MIS, SAP, Abhinav Bajpai'},
    'impact.html':{title:'Impact | Abhinav Bajpai — Supply Chain Scale & Business Outcomes',description:'Operating scale, measurable impact and supply-chain outcomes across Abhinav Bajpai’s commercial career.',keywords:'supply chain impact, commercial impact, 700 vehicles, liquid cargo, automation savings, Mundra, Abhinav Bajpai'},
    'case-studies.html':{title:'Case Studies | Abhinav Bajpai — Supply Chain & Commercial Transformation',description:'Flagship case studies covering commercial automation, dispatch, liquid cargo, GST analytics, global trade and procurement.',keywords:'supply chain case studies, commercial automation, dispatch, liquid cargo, GST analytics, global trade, procurement'},
    'projects.html':{title:'Projects | Abhinav Bajpai — GST, Logistics, Trade & Automation',description:'Selected commercial, supply-chain, GST, logistics, analytics and automation initiatives by Abhinav Bajpai.',keywords:'GST analysis, E-Way Bill, logistics, inventory, exports, global trade, procurement, Excel automation'},
    'awards.html':{title:'Awards & Recognition | Abhinav Bajpai',description:'Awards, promotions, scholarship, professional recognition and measurable commercial and supply-chain impact of Abhinav Bajpai.',keywords:'Abhinav Bajpai awards, AWL recognition, Employee of the Month, Long Service Award, MIT MicroMasters'},
    'contact.html':{title:'Contact Abhinav Bajpai | Commercial & Supply Chain Leadership',description:'Contact Abhinav Bajpai for commercial leadership, supply chain, procurement, operations excellence, global trade and transformation opportunities.',keywords:'contact Abhinav Bajpai, commercial leader, supply chain leader, procurement, operations'}
  };
  const p=pages[file]||pages['index.html'];
  const canonical=base+(file==='index.html'?'':('/'+file));
  document.title=p.title;
  const set=(name,content)=>{let el=document.querySelector('meta[name="'+name+'"]');if(!el){el=document.createElement('meta');el.name=name;document.head.appendChild(el)}el.content=content};
  set('description',p.description);set('keywords',p.keywords);set('robots','index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1');
  let link=document.querySelector('link[rel="canonical"]');if(!link){link=document.createElement('link');link.rel='canonical';document.head.appendChild(link)}link.href=canonical;
  const og={'og:type':'website','og:url':canonical,'og:title':p.title,'og:description':p.description,'og:site_name':'Abhinav Bajpai','og:locale':'en_IN','og:image':base+'/assets/abhinav-bajpai-professional.png','twitter:card':'summary_large_image','twitter:title':p.title,'twitter:description':p.description,'twitter:image':base+'/assets/abhinav-bajpai-professional.png'};
  Object.entries(og).forEach(([name,content])=>{let el=document.querySelector('meta[property="'+name+'"],meta[name="'+name+'"]');if(!el){el=document.createElement('meta');if(name.startsWith('twitter:'))el.name=name;else el.setAttribute('property',name);document.head.appendChild(el)}el.content=content});
  const person={'@type':'Person','@id':base+'/#person','name':'Abhinav Bajpai','url':base+'/','image':base+'/assets/abhinav-bajpai-professional.png','jobTitle':'Associate Manager — Commercial & Supply Chain','description':'Commercial and Supply Chain professional with 15+ years of experience across procurement, logistics, imports, exports, finance, warehouse, dispatch, GST, Customs and process automation.','sameAs':['https://www.linkedin.com/in/abhinavbajpai'],'worksFor':{'@type':'Organization','name':'AWL Agri Business Limited','url':'https://www.awl.in/'},'knowsAbout':['Supply Chain Management','Commercial Operations','Procurement','Warehouse Operations','Dispatch','Logistics','Imports','Exports','GST','Customs','E-Way Bills','Invoice Controls','Excel Automation','MIS','Mundra Port Operations','Liquid Cargo','Stores Management']};
  const graph=[person,{'@type':'WebSite','@id':base+'/#website','url':base+'/','name':'Abhinav Bajpai — Commercial & Supply Chain Leader','publisher':{'@id':base+'/#person'}},{'@type':'WebPage','@id':canonical+'#webpage','url':canonical,'name':p.title,'description':p.description,'isPartOf':{'@id':base+'/#website'},'about':{'@id':base+'/#person'},'inLanguage':'en-IN','keywords':p.keywords}];
  let ld=document.getElementById('abhinav-seo-jsonld');if(!ld){ld=document.createElement('script');ld.id='abhinav-seo-jsonld';ld.type='application/ld+json';document.head.appendChild(ld)}ld.textContent=JSON.stringify({'@context':'https://schema.org','@graph':graph});
})();
