/* SEO foundation for abhinavbajpai.in */
(function(){
  const base='https://abhinavbajpai.in';
  const path=location.pathname.replace(/^\/+/,'').toLowerCase()||'index.html';
  const file=path.split('/').pop();
  const pages={
    'index.html':{title:'Abhinav Bajpai | Supply Chain Professional & Commercial Leader',description:'Abhinav Bajpai is a supply chain professional and commercial leader with 15+ years across AWL Agri Business (formerly Adani Wilmar), Mundra operations, procurement, logistics, global trade, GST, Customs and commercial automation.',keywords:'Abhinav Bajpai, supply chain professional, supply chain leader, commercial leader, supply chain management India, supply chain consultant, supply chain consultation, Adani Wilmar, AWL Agri Business, Mundra, procurement, logistics, global trade, GST, Customs, supply chain automation'},
    'profile.html':{title:'Profile | Abhinav Bajpai — Commercial & Supply Chain Leader',description:'Executive profile covering commercial leadership, supply chain, procurement, exports, finance, warehouse, logistics, GST, Customs and data-driven operations.',keywords:'Abhinav Bajpai profile, supply chain, commercial operations, procurement, warehouse, dispatch, GST, Customs, exports, imports'},
    'experience.html':{title:'Experience | Abhinav Bajpai — 15+ Years Supply Chain Professional',description:'15+ years of commercial and supply-chain experience across AWL Agri Business (formerly Adani Wilmar), Mundra, Roca and Action Construction Equipment.',keywords:'Abhinav Bajpai experience, supply chain professional, supply chain experience, AWL, Adani Wilmar, Mundra, exports, finance, warehouse, procurement, logistics, commercial'},
    'capabilities.html':{title:'Supply Chain Capabilities | Abhinav Bajpai — India',description:'Supply chain and commercial capabilities across procurement, logistics, global trade, operations, GST, Customs, MIS and process automation.',keywords:'supply chain capabilities, supply chain professional, supply chain management, supply chain procurement, logistics, commercial operations, global trade, GST, Customs, Excel automation, MIS, SAP, Abhinav Bajpai'},
    'impact.html':{title:'Supply Chain Impact | Abhinav Bajpai — Mundra & AWL',description:'Supply-chain operating scale and commercial outcomes from Abhinav Bajpai’s experience at AWL Agri Business, formerly Adani Wilmar, including Mundra operations.',keywords:'supply chain impact, supply chain professional, AWL Agri Business, Adani Wilmar, Mundra supply chain, commercial impact, 700 vehicles, liquid cargo, automation, Abhinav Bajpai'},
    'case-studies.html':{title:'Case Studies | Abhinav Bajpai — Supply Chain & Commercial Transformation',description:'Flagship case studies covering commercial automation, dispatch, liquid cargo, GST analytics, global trade and procurement.',keywords:'supply chain case studies, commercial automation, dispatch, liquid cargo, GST analytics, global trade, procurement'},
    'projects.html':{title:'Supply Chain Projects | Abhinav Bajpai — Logistics, Trade & Automation',description:'Selected supply-chain, commercial, GST, logistics, global trade, procurement and automation projects by Abhinav Bajpai.',keywords:'supply chain projects, supply chain professional, GST analysis, E-Way Bill, logistics, inventory, exports, global trade, procurement, Excel automation'},
    'awards.html':{title:'Awards & Recognition | Abhinav Bajpai — Supply Chain Professional',description:'Recognition, promotions, scholarship and professional achievements of Abhinav Bajpai across commercial and supply-chain leadership.',keywords:'Abhinav Bajpai awards, supply chain professional recognition, AWL recognition, Adani Wilmar, Employee of the Month, Long Service Award, MIT MicroMasters'},
    'contact.html':{title:'Supply Chain Consultation | Abhinav Bajpai — India',description:'Supply chain consultation and commercial advisory by Abhinav Bajpai, a 15+ year supply chain professional with AWL Agri Business, formerly Adani Wilmar, and experience across procurement, logistics, global trade, GST, Customs and automation.',keywords:'supply chain consultation, supply chain consultant India, supply chain professional India, Abhinav Bajpai consultant, commercial consultant, supply chain advisory, procurement consultant, logistics consultant, Adani Wilmar supply chain, AWL Agri Business'},
    'supply-chain-consultation.html':{title:'Supply Chain Consultation India | Abhinav Bajpai',description:'Private supply chain consultation in India by Abhinav Bajpai, a 15+ year supply chain professional with AWL Agri Business, formerly Adani Wilmar.',keywords:'supply chain consultation, supply chain consultant India, supply chain professional, supply chain advisory, commercial consultant, procurement consultant, logistics consultant, Adani Wilmar, AWL Agri Business, Mundra supply chain, Abhinav Bajpai'},
    'supply-chain-consultant-india.html':{title:'Supply Chain Consultant India | Abhinav Bajpai',description:'Practical supply chain consulting insights from Abhinav Bajpai, a 15+ year supply chain professional.',keywords:'supply chain consultant India, supply chain consultation, supply chain professional, Abhinav Bajpai'},
    'supply-chain-management-india.html':{title:'Supply Chain Management in India | Abhinav Bajpai',description:'Practical supply chain management perspective covering procurement, logistics, commercial control and operations.',keywords:'supply chain management India, supply chain professional, procurement, logistics, Abhinav Bajpai'},
    'commercial-vs-supply-chain.html':{title:'Commercial vs Supply Chain | Abhinav Bajpai',description:'How commercial control and physical supply-chain execution connect in complex operations.',keywords:'commercial supply chain, supply chain professional, commercial operations, Abhinav Bajpai'},
    'mundra-supply-chain-operations.html':{title:'Mundra Supply Chain Operations | Abhinav Bajpai',description:'A practical perspective on port-to-plant-to-market supply chain operations at Mundra.',keywords:'Mundra supply chain, Adani Wilmar, AWL, supply chain professional, port operations'},
    'gst-customs-supply-chain.html':{title:'GST and Customs in Supply Chain | Abhinav Bajpai',description:'How GST, Customs, documentation and commercial controls connect with supply-chain execution.',keywords:'GST supply chain, Customs supply chain, commercial control, supply chain professional'},
    'high-volume-dispatch.html':{title:'High Volume Dispatch Operations | Abhinav Bajpai',description:'A practical framework for vehicle planning, dispatch control, logistics and operational visibility.',keywords:'high volume dispatch, logistics, supply chain professional, dispatch operations, Abhinav Bajpai'},
    'insights/index.html':{title:'Supply Chain Insights | Abhinav Bajpai',description:'Supply chain, commercial, procurement, logistics, GST, Customs and operations insights from Abhinav Bajpai.',keywords:'supply chain insights, supply chain professional, supply chain management, commercial operations, procurement, logistics, Abhinav Bajpai'}
  };
  const p=pages[path]||pages[file]||pages['index.html'];
  const canonical=base+'/'+path;
  document.title=p.title;
  const set=(name,content)=>{let el=document.querySelector('meta[name="'+name+'"]');if(!el){el=document.createElement('meta');el.name=name;document.head.appendChild(el)}el.content=content};
  set('description',p.description);set('keywords',p.keywords);set('robots','index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1');
  let link=document.querySelector('link[rel="canonical"]');if(!link){link=document.createElement('link');link.rel='canonical';document.head.appendChild(link)}link.href=canonical;
  const og={'og:type':'website','og:url':canonical,'og:title':p.title,'og:description':p.description,'og:site_name':'Abhinav Bajpai','og:locale':'en_IN','og:image':base+'/assets/abhinav-bajpai-professional.png','twitter:card':'summary_large_image','twitter:title':p.title,'twitter:description':p.description,'twitter:image':base+'/assets/abhinav-bajpai-professional.png'};
  Object.entries(og).forEach(([name,content])=>{let el=document.querySelector('meta[property="'+name+'"],meta[name="'+name+'"]');if(!el){el=document.createElement('meta');if(name.startsWith('twitter:'))el.name=name;else el.setAttribute('property',name);document.head.appendChild(el)}el.content=content});
  const person={'@type':'Person','@id':base+'/#person','name':'Abhinav Bajpai','url':base+'/','image':base+'/assets/abhinav-bajpai-professional.png','jobTitle':'Associate Manager — Commercial & Supply Chain','description':'Commercial and Supply Chain professional with 15+ years of experience across procurement, logistics, imports, exports, finance, warehouse, dispatch, GST, Customs and process automation.','sameAs':['https://www.linkedin.com/in/abhinavbajpai'],'worksFor':{'@type':'Organization','name':'AWL Agri Business Limited','url':'https://www.awl.in/'},'knowsAbout':['Supply Chain Management','Commercial Operations','Procurement','Warehouse Operations','Dispatch','Logistics','Imports','Exports','GST','Customs','E-Way Bills','Invoice Controls','Excel Automation','MIS','Mundra Port Operations','Liquid Cargo','Stores Management']};
  const website={'@type':'WebSite','@id':base+'/#website','url':base+'/','name':'Abhinav Bajpai — Commercial & Supply Chain Leader','publisher':{'@id':base+'/#person'}};
  const webpage={'@type':'WebPage','@id':canonical+'#webpage','url':canonical,'name':p.title,'description':p.description,'isPartOf':{'@id':base+'/#website'},'about':{'@id':base+'/#person'},'inLanguage':'en-IN','keywords':p.keywords};
  const graph=[person,website,webpage];
  if(file==='profile.html'){graph.push({'@type':'ProfilePage','@id':canonical+'#profile','url':canonical,'mainEntity':{'@id':base+'/#person'},'isPartOf':{'@id':base+'/#website'}})}
  const insight=path.startsWith('insights/');
  if(insight){graph.push({'@type':'Article','@id':canonical+'#article','url':canonical,'headline':p.title,'description':p.description,'author':{'@id':base+'/#person'},'publisher':{'@id':base+'/#person'},'mainEntityOfPage':{'@id':canonical+'#webpage'},'inLanguage':'en-IN'})}
  if(file==='supply-chain-consultation.html'||file==='contact.html'){graph.push({'@type':'Service','@id':canonical+'#service','name':'Supply Chain Consultation','serviceType':'Supply Chain Consultation and Commercial Advisory','provider':{'@id':base+'/#person'},'areaServed':{'@type':'Country','name':'India'},'url':canonical,'offers':{'@type':'Offer','priceCurrency':'INR','price':'12000-15000','description':'Private consultation rate per hour; final fee depends on scope, complexity and preparation required.'}})}
  const crumbs=[{'@type':'ListItem','position':1,'name':'Home','item':base+'/'}];
  if(insight){crumbs.push({'@type':'ListItem','position':2,'name':'Insights','item':base+'/insights/'});}
  if(file!=='index.html')crumbs.push({'@type':'ListItem','position':insight?3:2,'name':p.title,'item':canonical});
  graph.push({'@type':'BreadcrumbList','@id':canonical+'#breadcrumb','itemListElement':crumbs});
  let ld=document.getElementById('abhinav-seo-jsonld');if(!ld){ld=document.createElement('script');ld.id='abhinav-seo-jsonld';ld.type='application/ld+json';document.head.appendChild(ld)}ld.textContent=JSON.stringify({'@context':'https://schema.org','@graph':graph});
})();